mod extractors;

use axum::extract::Path;
use axum::http::StatusCode;
use axum::{Json, Router, routing::get};
use axum::routing::patch;
use rustflow_common::{
    APP_NAME, APP_VERSION, CreateTask, HealthStatus, Priority, Task, TaskFilter, TaskStatus,
};
use tokio::net::TcpListener;
use crate::extractors::{ValidatedJson, ValidatedQuery};

/// Root endpoint - a simple liveness message
async fn root() -> &'static str {
    "RustFlow is running!"
}

/// Health check endpoint - returns structured JSON about the service
async fn health() -> axum::Json<HealthStatus> {
    axum::Json(HealthStatus::default())
}

/// GET /tasks?status=pending&priority=high
///
/// The ValidatedQuery extractor deserializes and validates query parameters into a TaskFilter struct.
async fn list_tasks(ValidatedQuery(filter): ValidatedQuery<TaskFilter>) -> Json<Vec<Task>> {
    let tasks = sample_tasks();

    let filtered: Vec<Task> = tasks
        .into_iter()
        .filter(|task| filter.status.as_ref().map_or(true, |s| &task.status == s))
        .filter(|task| filter.status.as_ref().map_or(true, |s| &task.status == s))
        .filter(|task| filter.search.as_ref().map_or(true, |s| task.title.contains(s) || task.description.as_ref().map_or(false, |d| d.contains(s))))
        .collect();

    Json(filtered)
}

/// GET /tasks/:id
///
/// The Path extractor captures the `id` from the URL and looks up the corresponding task.
/// If the task is found, it returns it as JSON. If not, it returns a 404 Not Found status.
/// Axum automatically returns 400 Bad Request if the `id` cannot be parsed as a u64.
async fn get_task(Path(id): Path<u64>) -> Result<Json<Task>, StatusCode> {
    let tasks = sample_tasks();
    tasks
        .into_iter()
        .find(|task| task.id == id)
        .map(Json)
        .ok_or(StatusCode::NOT_FOUND)
}

async fn create_task(ValidatedJson(payload): ValidatedJson<CreateTask>) -> (StatusCode, Json<Task>) {
    let task = Task {
        id: 999, // In a real app, this would be generated by the database
        title: payload.title,
        description: payload.description,
        priority: payload.priority,
        status: TaskStatus::Pending,
    };

    (StatusCode::CREATED, Json(task))
}

async fn update_task(
    Path(id): Path<u64>,
    ValidatedJson(payload): ValidatedJson<CreateTask>,
) -> Result<Json<Task>, StatusCode> {
    let mut tasks = sample_tasks();
    if let Some(task) = tasks.iter_mut().find(|task| task.id == id) {
        task.title = payload.title;
        task.description = payload.description;
        task.priority = payload.priority;
        Ok(Json(task.clone()))
    } else {
        Err(StatusCode::NOT_FOUND)
    }
}

async fn change_task_status(
    Path(id): Path<u64>,
    Json(payload): Json<TaskStatus>,
) -> Result<Json<Task>, StatusCode> {
    let mut tasks = sample_tasks();
    if let Some(task) = tasks.iter_mut().find(|task| task.id == id) {
        task.status = payload;
        Ok(Json(task.clone()))
    } else {
        Err(StatusCode::NOT_FOUND)
    }
}


// ── Helpers ─────────────────────────────────────────────────

fn sample_tasks() -> Vec<Task> {
    vec![
        Task {
            id: 1,
            title: "Set up workspace".into(),
            description: Some("Initialize the Cargo workspace".into()),
            priority: Priority::High,
            status: TaskStatus::Done,
        },
        Task {
            id: 2,
            title: "Add Axum".into(),
            description: Some("Create the HTTP server".into()),
            priority: Priority::High,
            status: TaskStatus::InProgress,
        },
        Task {
            id: 3,
            title: "Write extractors lesson".into(),
            description: None,
            priority: Priority::Medium,
            status: TaskStatus::Pending,
        },
    ]
}

#[tokio::main]
async fn main() {
    // Build the application router
    let app = Router::new()
        .route("/", get(root))
        .route("/health", get(health))
        .route("/tasks", get(list_tasks).post(create_task))
        .route("/tasks/{id}", get(get_task).put(update_task))
        .route("/tasks/{id}/status", patch(change_task_status));

    let addr = "0.0.0.0:3000";
    let listener = TcpListener::bind(addr)
        .await
        .expect("Failed to bind to address");

    println!("{} v{} listening on {}", APP_NAME, APP_VERSION, addr);

    axum::serve(listener, app).await.expect("Server error");
}
